services:
  app-spring-boot:
    build:
      context: .
      dockerfile: ./services/spring/Dockerfile
    container_name: spring-atendimento-apae
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8080:8080"
    networks:
      - public-network
      - private-network
    depends_on:
      - postgres-db
      - minio
      
  minio:
    image: minio-atendimento-apae
    build:
      context: ./services/minio
      dockerfile: Dockerfile
    container_name: minio-atendimento-apae
    restart: always
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - public-network
    volumes:
      - minio-data:/var/lib/minio/data

  postgres-db:
    image: postgres-atendimento-apae-image
    build:
      context: ./services/postgres
      dockerfile: Dockerfile
    container_name: postgres-atendimento-apae
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - private-network

volumes:
  db-data:
    driver: local
  minio-data:
    driver: local

networks:
  private-network:
    driver: bridge
    internal: true
  public-network:
    driver: bridge
