services:
  minio:
    image: minio/minio:latest
    container_name: minio-atendimento-apae
    command: server /data --console-address ":9001"
    restart: always
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - public-network
    volumes:
      - minio-data:/data

volumes:
  db-data:
  minio-data:
   

networks:
  private-network:
    
  
