services:
  postgres-db:
    image: postgres:16
    container_name: postgres-atendimento-apae
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    command: >
      postgres
      -c listen_addresses='*'
      -c port=5432

  minio:
    image: minio/minio:latest
    container_name: minio-atendimento-apae
    command: server /data --console-address ":9001"
    restart: always
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  db-data:
  minio-data: