services:
  postgres-db:
    image: postgres:16
    container_name: postgres-atendimento-apae
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - private-network
    command: >
      postgres
      -c listen_addresses='*'
      -c port=5432

volumes:
  db-data:
    driver: local
  minio-data:
    driver: local

networks:
  private-network:
    driver: bridge
  public-network:
    driver: bridge
