services:
  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    container_name: minio-atendimento-apae
    command: server /data --console-address ":9001"
    restart: always
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - public-network
    volumes:
      - minio-data:/var/lib/minio/data

volumes:
  db-data:
    driver: local
  minio-data:
    driver: local

networks:
  private-network:
    driver: bridge
  public-network:
    driver: bridge
