name: CI Front-end

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'frontend/**'

jobs:
  build:
    name: Build do projeto Front-end
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar PNPM
        uses: pnpm/action-setup@v4
        with:
          version: "11.1.2"
          run_install: false

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.13"
          cache: "pnpm"
          cache-dependency-path: frontend/atendimento-app/pnpm-lock.yaml

          name: CI Front-end

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'frontend/**'

jobs:
  build:
    name: Build do projeto Front-end
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

        - name: Aprovar builds do pnpm
        working-directory: ./frontend/atendimento-app
        run: pnpm approve-builds

      - name: Instalar PNPM
        uses: pnpm/action-setup@v4
        with:
          version: "11.1.2"
          run_install: false

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.13"
          cache: "pnpm"
          cache-dependency-path: frontend/atendimento-app/pnpm-lock.yaml

      - name: Instalar dependências
        working-directory: ./frontend/atendimento-app
        run: pnpm install --frozen-lockfile

      - name: Construir aplicação
        working-directory: ./frontend/atendimento-app
        run: pnpm run build

      - name: Salvar artefato de build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/atendimento-app/.next

      - name: Instalar dependências
        working-directory: ./frontend/atendimento-app
        run: pnpm install --frozen-lockfile

      - name: Construir aplicação
        working-directory: ./frontend/atendimento-app
        run: pnpm run build

      - name: Salvar artefato de build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/atendimento-app/.next
