# application-test.properties

# Datasource já em PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/atendimento_apae_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SQL
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=false
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data-test.sql

# Minio
minio.endpoint=http://localhost:9000
minio.root.user=minio
minio.root.password=minio123

bucket.name=apae

# Front
cors.allowed-origins=http://localhost:3000

# Firebase desabilitado em test
firebase.enabled=false


mock.user.id=44444444-4444-4444-4444-444444444444