spring.config.import=optional:file:../docker/docker-compose.properties

# Firebase desabilitado em dev
firebase.enabled=false

# ID do usuario injetado automaticamente quando o Firebase esta desabilitado
#mock.user.id=