spring.config.import=optional:file:../docker/docker-compose.properties

# Firebase desabilitado em dev
firebase.enabled=false

# ID do usuário injetado automaticamente quando o Firebase está desabilitado
#mock.user.id=